version: '3'
services:
  web:
    build: ./
    ports:
    - "8080:5000"
    environment:
      NODE_ENV: dev
      CONTAINER_IP: 0.0.0.0
      CONTAINER_PORT: 5000
    volumes:
    - ./:/var/www
    - /usr/lib/node_modules/nodemon:/usr/lib/node_modules/nodemon
